### ISSUE TITLE
Invalid redirection URL

### ISSUE THREAD

**Issue by pelzvieh** [matrix-org/matrix-static#75]
The following URL is generated from matrix.to for the matrix-static client:

> https://view.matrix.org/room/!qIEpwTKYYJECuPNzlt:flying-snail-matrix.nsupdate.info?via=flying-snail-matrix.nsupdate.info&via=matrix.org

Calling this redirects to the following, obviously invalid, URL:

> https://matrix.orgroom/!qIEpwTKYYJECuPNzlt:flying-snail-matrix.nsupdate.info?via=flying-snail-matrix.nsupdate.info&via=matrix.org

(server "matrix.orgroom" cannot be found)

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix.org/issues/379
